### ISSUE TITLE
In normal mode, no variable insert ...

### ISSUE THREAD

**Issue by ChrisGitIt** [glippi/lognroll-vim#4]
Hi and thanks for this nice plugin (don't know how many time i have written "console.log").

Somehow, its not working for me. When I'm in insert or normal mode and I do "cll", only "console.log({})" is printed out with no vars included (yes, my cursor was over a variable).

Any clues how I could debug this issue und see what's going wrong?

Also some suggestions:
- Using "console" is actually a bad practice and its probably better to use a logging library like "Pino" or something alike. I think it would be nice if there could be "snippets" for the four different logging mechanisms. like "let lognroll_console_log = 'pino.log($$)'" OR "let lognroll_console_warning = 'pino.warning($$)'"....

- Would it be possible to log several vars at once? I often have functions/methods with more than one parameter and I would like to log them in one go. So "function(var1, var2)" would / should resolve to "console.log(var1, var2)", maybe with something like "clla" (log all) or "cll2" (log two vars) ...

- Would it be possible to include the "calling function" if its used on functions vars?
Like "function myFunc(var1, var2)" would result in "console.log('myFunc:', var1, var2)"

Also some questions:
- What are the curly brackets supposed to do in "console.log({})" ?? When I use them in the browser (FF), I will get an object for my string variable (var a = 'test'; console.log({a})) => {a:test})). In older browsers (especially mobil), this results in an error.

Okay, I think that's all for now.

Greetings,

Chris

**Comment by glippi** [comment]
Hi @ChrisGitIt, I'm glad you're finding useful.

> When I'm in insert or normal mode and I do "cll", only "console.log({})" is printed out with no vars included (yes, my cursor was over a variable).

I've just updated the plugin yesterday, so in `NORMAL MODE` it should work as you expected, so typing `cll` should print the variable one line below the line where the variable is.
But now, `INSERT MODE` mapping are disabled by default. In order to use them you should add this line inside your `.vimrc`: `let g:lognroll_vim#enable_insert_mode = 1`.
My bad, but I did not have time yet to update the README.
I suggest to do a `PlugUpdate`.

About the suggestions, all interesting but:

   1) Honestly, I wouldn't say that is a bad practice to use "console". Anyway, It could be something interesting to work on it. If you want to open a PR, it's welcome!

   2) Logging all the variables inside a function calls it's something that I think it's not possible to implement with the design choice I made here, because the mapping `yiwo` by definition yanks only one word, so can't access the other variable. But it seems to me very reasonable and useful the point you are raising, and it's something I will try to work on, again if you have some ideas and want to open a PR it'd be great

  3) See the previous point

  4) The curly brackets are a shortcut to avoid typing things like `var a = 'dumb string' console.log('a', a)` 


Let me know if you are still having the same error, and for the rest, if you have any further questions, don't hesitate to ask

**Comment by ChrisGitIt** [comment]
Hi @glippi,

and thanks for your reply. I just did a plugin update a minute ago, but the empty console.log issue is still there... 

I'm not sure if I should start with a blanko vim to narrow down the problem or if there is a "debug" mode that I can enable to see if its actually a problem with your plugin.

Greetings,

Chris

**Comment by glippi** [comment]
Hi @ChrisGitIt,
I worked a lot on the plugin this weekend, I've implented some of the things you were looking for, like:

  * possibility to use another logger, like Pino
  * possibility to log all the variables inside a pair of brackets
  * possibility to remove curly brackets from log

:warning: I also made a breaking change, now the mapping for log is `col` for `console.log`, anyway it's possible to remap to another keystroke using `<Plug>`

More info in the `README`.
